# Generated by Django 3.2 on 2023-04-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoDetalle',
        ),
    ]
